name: gtk_application_example
description: Demonstrates how to use the gtk_application plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  gtk_application:
    path: ../
  yaru: ^0.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
