name: gtk_application
description: |
  Listen to remote GtkApplication instances' command-line arguments and file
  open requests.
homepage: https://github.com/jpnurmi/gtk_application.dart
repository: https://github.com/jpnurmi/gtk_application.dart
issue_tracker: https://github.com/jpnurmi/gtk_application.dart/issues
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: GtkApplicationPlugin
