name: gtk_application
description: |
  Listen to remote GtkApplication instances' command-line arguments and file
  open requests.
homepage: https://github.com/jpnurmi/gtk_application.dart
repository: https://github.com/jpnurmi/gtk_application.dart
issue_tracker: https://github.com/jpnurmi/gtk_application.dart/issues
version: 0.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: GtkApplicationPlugin
